/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PathwaysRouteImport } from './routes/pathways'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicationsIndexRouteImport } from './routes/publications.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LearningIndexRouteImport } from './routes/learning.index'
import { Route as PublicationsPublicationIdRouteImport } from './routes/publications.$publicationId'
import { Route as LibraryResourceIdRouteImport } from './routes/library.$resourceId'
import { Route as LearningCourseIdRouteImport } from './routes/learning.$courseId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminEditorialRouteImport } from './routes/admin/editorial'
import { Route as AdminConferencesRouteImport } from './routes/admin/conferences'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysRoute = PathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsIndexRoute = PublicationsIndexRouteImport.update({
  id: '/publications/',
  path: '/publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsPublicationIdRoute =
  PublicationsPublicationIdRouteImport.update({
    id: '/publications/$publicationId',
    path: '/publications/$publicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryResourceIdRoute = LibraryResourceIdRouteImport.update({
  id: '/library/$resourceId',
  path: '/library/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCourseIdRoute = LearningCourseIdRouteImport.update({
  id: '/learning/$courseId',
  path: '/learning/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorialRoute = AdminEditorialRouteImport.update({
  id: '/admin/editorial',
  path: '/admin/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConferencesRoute = AdminConferencesRouteImport.update({
  id: '/admin/conferences',
  path: '/admin/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conference': typeof ConferenceRoute
  '/dashboard': typeof DashboardRoute
  '/pathways': typeof PathwaysRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/conferences': typeof AdminConferencesRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/learning/$courseId': typeof LearningCourseIdRoute
  '/library/$resourceId': typeof LibraryResourceIdRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/learning/': typeof LearningIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/publications/': typeof PublicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conference': typeof ConferenceRoute
  '/dashboard': typeof DashboardRoute
  '/pathways': typeof PathwaysRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/conferences': typeof AdminConferencesRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/learning/$courseId': typeof LearningCourseIdRoute
  '/library/$resourceId': typeof LibraryResourceIdRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/learning': typeof LearningIndexRoute
  '/library': typeof LibraryIndexRoute
  '/publications': typeof PublicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conference': typeof ConferenceRoute
  '/dashboard': typeof DashboardRoute
  '/pathways': typeof PathwaysRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/conferences': typeof AdminConferencesRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/learning/$courseId': typeof LearningCourseIdRoute
  '/library/$resourceId': typeof LibraryResourceIdRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/learning/': typeof LearningIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/publications/': typeof PublicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conference'
    | '/dashboard'
    | '/pathways'
    | '/profile'
    | '/templates'
    | '/admin/analytics'
    | '/admin/conferences'
    | '/admin/editorial'
    | '/admin/registrations'
    | '/admin/users'
    | '/learning/$courseId'
    | '/library/$resourceId'
    | '/publications/$publicationId'
    | '/learning/'
    | '/library/'
    | '/publications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conference'
    | '/dashboard'
    | '/pathways'
    | '/profile'
    | '/templates'
    | '/admin/analytics'
    | '/admin/conferences'
    | '/admin/editorial'
    | '/admin/registrations'
    | '/admin/users'
    | '/learning/$courseId'
    | '/library/$resourceId'
    | '/publications/$publicationId'
    | '/learning'
    | '/library'
    | '/publications'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/conference'
    | '/dashboard'
    | '/pathways'
    | '/profile'
    | '/templates'
    | '/admin/analytics'
    | '/admin/conferences'
    | '/admin/editorial'
    | '/admin/registrations'
    | '/admin/users'
    | '/learning/$courseId'
    | '/library/$resourceId'
    | '/publications/$publicationId'
    | '/learning/'
    | '/library/'
    | '/publications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConferenceRoute: typeof ConferenceRoute
  DashboardRoute: typeof DashboardRoute
  PathwaysRoute: typeof PathwaysRoute
  ProfileRoute: typeof ProfileRoute
  TemplatesRoute: typeof TemplatesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminConferencesRoute: typeof AdminConferencesRoute
  AdminEditorialRoute: typeof AdminEditorialRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LearningCourseIdRoute: typeof LearningCourseIdRoute
  LibraryResourceIdRoute: typeof LibraryResourceIdRoute
  PublicationsPublicationIdRoute: typeof PublicationsPublicationIdRoute
  LearningIndexRoute: typeof LearningIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  PublicationsIndexRoute: typeof PublicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways': {
      id: '/pathways'
      path: '/pathways'
      fullPath: '/pathways'
      preLoaderRoute: typeof PathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/': {
      id: '/publications/'
      path: '/publications'
      fullPath: '/publications/'
      preLoaderRoute: typeof PublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$publicationId': {
      id: '/publications/$publicationId'
      path: '/publications/$publicationId'
      fullPath: '/publications/$publicationId'
      preLoaderRoute: typeof PublicationsPublicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$resourceId': {
      id: '/library/$resourceId'
      path: '/library/$resourceId'
      fullPath: '/library/$resourceId'
      preLoaderRoute: typeof LibraryResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$courseId': {
      id: '/learning/$courseId'
      path: '/learning/$courseId'
      fullPath: '/learning/$courseId'
      preLoaderRoute: typeof LearningCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editorial': {
      id: '/admin/editorial'
      path: '/admin/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AdminEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conferences': {
      id: '/admin/conferences'
      path: '/admin/conferences'
      fullPath: '/admin/conferences'
      preLoaderRoute: typeof AdminConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConferenceRoute: ConferenceRoute,
  DashboardRoute: DashboardRoute,
  PathwaysRoute: PathwaysRoute,
  ProfileRoute: ProfileRoute,
  TemplatesRoute: TemplatesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminConferencesRoute: AdminConferencesRoute,
  AdminEditorialRoute: AdminEditorialRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  LearningCourseIdRoute: LearningCourseIdRoute,
  LibraryResourceIdRoute: LibraryResourceIdRoute,
  PublicationsPublicationIdRoute: PublicationsPublicationIdRoute,
  LearningIndexRoute: LearningIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  PublicationsIndexRoute: PublicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
